### ISSUE TITLE
MR24HPC1.yaml reports detection/motion but no other parameters

### ISSUE THREAD

**Issue by WheresWes** [limengdu/mmwave-kit-external-components#5]
Using the MR24HPC1.yaml example file for the Human Presence Detection Kit in the ESPHome environment.  When I compile and flash the ESP from ESPHome and import the device into home assistant I get reporting of:
Presence Information
Body Movement Parameter
Motion Information

But most of the other parameters are not being updated ie:
Motion Distance
Motion Speed
Static Distance
Existance Energy
Motion Energy

Also time for entering no person state value cannot be changed - always reverts back to 30s

**Comment by drothenberger** [comment]
I believe you only get reporting for the other parameters when the "Underlying Open Function Info Output Switch" is on.

I don't have any problems changing the "Entering No Person State" value. Which one are you trying to adjust? The regular one with a drop-down, or the one for the underlying open function info state, which is a text field in Home Assistant?

**Comment by WheresWes** [comment]
Thanks for the quick reply.. Yes bingo on the "Underlying Open Function Info Output Switch" values are now being reported!

I was trying to change the regular one with the drop down... But playing with the text field does seem to work.  What is the difference between the two?  I'm struggling a little for lack of documentation on this.  Is there somewhere which describes the sensor outputs / setings?

**Comment by drothenberger** [comment]
> I was trying to change the regular one with the drop down... But playing with the text field does seem to work. What is the difference between the two? I'm struggling a little for lack of documentation on this. Is there somewhere which describes the sensor outputs / setings?

According to the labels, I think the text field is for when the Underlying Open Function Info is enabled, and the drop-down is for when it's disabled. I've personally only turned on the Underlying Open Function to watch the values in real-time, and then turned it off for regular operation, so I've never played with the text field.

The documentation is hard to find, but you can find descriptions of all these things in the [user manual](https://files.seeedstudio.com/wiki/mmWave-radar/MR24HPC1_User_Manual-V1.5.pdf).
