### ISSUE TITLE
Documentation for optimizing performance

### ISSUE THREAD

**Issue by Motya-HA** [limengdu/mmwave-kit-external-components#7]
Hello
I am using the kit with you code and I see a lot of entities that should be optimized. Do you have tetorial or some other documentation to do so?

**Comment by limengdu** [comment]
Since the folks at ESPHome haven't merged our commits yet, the documentation is currently only available in a preview version.
https://deploy-preview-3383--esphome.netlify.app/components/sensor/seeed_mr24hpc1
