### ISSUE TITLE
mr24hpcb1 mmWave sensor

### ISSUE THREAD

**Issue by Motya-HA** [limengdu/mmwave-kit-external-components#8]
Please refer me to yaml code that will be working with mr24hpb1 sensor
I saw you have mentioned that other sensor will be supported later. Do you have timeline for different seeed studio mmWave sensors?

**Comment by limengdu** [comment]
It depends on when the ESPHome folks have time to merge our PR submissions for the MR24HPC1, otherwise we're holding off on starting development of the sensor after that. If we don't get the merge, all we've done is pointless. But for sure, we won't be doing ESPHome support for the MR24HPB1, it's an obsolete product.

**Comment by Motya-HA** [comment]
I used this forum to bring up MR24PB1: 
https://forum.seeedstudio.com/t/mmwave-human-detection-kit-and-mr24hpb1-sensor/272616
It works very stable, but unfortunately I can't adjust anything (sensitivity, max distance ect)

MR24PC1 has too many parameters to adjust, I did not find tutorial/documentation to get all settings right. Should MR24PC1 perform as well as MR24PB1 for static detection?

**Comment by limengdu** [comment]
The MR24HPC1 is well optimised for both static and dynamic detection algorithms. It offers a very rich set of scene customisations to provide the ability to detect the presence of the human body in complex environments, if you only need the simple functionality of a preset scene then you can refer to the documentation below to complete a quick setup:

https://files.seeedstudio.com/wiki/mmWave-radar/MR24HPC1_Quick_Setup_Template-V1.0.pdf

In ESPHome, you only need to complete the basic setup of scene and sensitivity.

If you want to be able to use it with as little parameter adjustment as possible, consider using mmwave for XIAO, a radar that requires little parameter adjustment and is quick to get started.
https://www.seeedstudio.com/Seeed-Studio-24GHz-mmWave-for-XIAO-p-5830.html

**Comment by Motya-HA** [comment]
I added mmWave for XIAO thought BLE

I can see yellow LED is solid and green LED is blinking. 
I see the following entities in HA
![Screenshot 2024-02-23 at 7 27 08 PM](https://github.com/limengdu/mmwave-kit-external-components/assets/143926968/2d71c531-65c4-419d-9b68-9394a5efcc2b)

How it is possible to add this sensor to ESPHome? Do you have YAML code that I can use?

**Comment by limengdu** [comment]
Hi, it doesn't need to go through ESPHome, there is a separate component for Bluetooth. Please refer to this Wiki:
https://wiki.seeedstudio.com/mmwave_for_xiao_to_ha_bt/

**Comment by Motya-HA** [comment]
I read this WiKi article and connected to BLE. I just thought that adding to ESPHome will let me do any setting optimization. Currently, in BLE integration I can't do anything, like change sensitivity or/and adjust max detectable range

**Comment by limengdu** [comment]
I understand your needs now, if you do need ESPHome support, you can read about this ld2410 product in ESPHome for now, they are compatible.
https://esphome.io/components/sensor/ld2410.html
