### ISSUE TITLE
MR24HPC1 advanced mode

### ISSUE THREAD

**Issue by Motya-HA** [limengdu/mmwave-kit-external-components#9]
Hello

Thank you for your previous response
I am trying to make MR24HPC1 work in Home Assistant
I can see the following entities (advanced mode on)

![Screenshot 2024-02-23 at 4 10 51 PM](https://github.com/limengdu/mmwave-kit-external-components/assets/143926968/7c6de1e7-951c-4d52-90cf-6a7f561076dc)
![Screenshot 2024-02-23 at 4 11 53 PM](https://github.com/limengdu/mmwave-kit-external-components/assets/143926968/b37cdda7-495d-4f59-ac60-c11a7526711b)

I made adjustments according to your suggested documentation, however, in "advanced mode" I do not obsessed any changes of the entity "Occupancy"

If I change "advanced mode off", I can see response of entity "occupancy" but:
1. Those are entities status: 

![Screenshot 2024-02-23 at 4 17 46 PM](https://github.com/limengdu/mmwave-kit-external-components/assets/143926968/a6d21e6b-4344-4aa5-8093-23ebb7268928)

2. Every time after restart, sensor changing "advanced mode on", and entity "occupancy stopes responding
What I am missing?

**Comment by limengdu** [comment]
It is recommended that you read the preview document here to understand the difference between Advanced and Standard modes.
https://deploy-preview-3383--esphome.netlify.app/components/sensor/seeed_mr24hpc1

Regarding your question, Occupancy is only reported by the radar in standard mode. In Advanced Mode, the Standard Mode features are automatically turned off, so you won't be able to see the contents of Occupancy, as well as Motion Information, Active Reporting Of Proximity, and all that data. Instead, you get Existence Energy, Distance, etc. in Advanced Mode.


Finally, the principle of updating these values in the standard model is that the radar reports when an update to the state occurs. So when you switch from Advanced Mode to Standard Mode, if the radar picks up that Occupancy's status hasn't changed, then you won't see the values reappear.

The above are definitions of the reporting methods and modes built into the radar firmware and have nothing to do with the ESPHome configuration code.
